name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Enable TS
        shell: pwsh
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
          
      - name: Set up udemy-py
        shell: cmd
        run: |
          git clone https://github.com/swargaraj/udemy-py.git
          curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          curl -L -o N_m3u8DL-RE.zip https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.2.1-beta/N_m3u8DL-RE_Beta_win-x64_20240828.zip
          curl -L -o bento4.zip https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-641.x86_64-microsoft-win32.zip

          mkdir temp
          tar -xf ffmpeg.zip -C temp
          tar -xf N_m3u8DL-RE.zip -C temp
          tar -xf bento4.zip -C temp

          ren temp\ffmpeg-master-latest-win64-gpl ffmpeg
          ren temp\N_m3u8DL-RE_Beta_win-x64 N_m3u8DL-RE
          ren temp\Bento4-SDK-1-6-0-641.x86_64-microsoft-win32 bento4

          mkdir bin

          echo Moving renamed directories to "bin" directory...
          xcopy /s /e /y temp\ffmpeg bin\ffmpeg\
          xcopy /s /e /y temp\N_m3u8DL-RE bin\N_m3u8DL-RE\
          xcopy /s /e /y temp\bento4 bin\bento4\

          set newPath=%CD%\bin\ffmpeg\bin;%CD%\bin\N_m3u8DL-RE;%CD%\bin\bento4\bin
          
          setx PATH "%newPath%;%PATH%"
          
          set PATH=%newPath%;%PATH%

          rmdir /s /q temp
          del ffmpeg.zip
          del N_m3u8DL-RE.zip
          del bento4.zip
          py -m pip install -r .\udemy-py\requirements.txt

      - name: Test Download
        shell: cmd
        run: |
          setx PATH "%CD%\bin\ffmpeg\bin;%CD%\bin\N_m3u8DL-RE;%CD%\bin\bento4\bin;%PATH%"
          set PATH=%CD%\bin\ffmpeg\bin;%CD%\bin\N_m3u8DL-RE;%CD%\bin\bento4\bin;%PATH%
          set PATH=%PATH%
          
      - name: Download and Extract ngrok for creating secure tunnels
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ".\ngrok.zip"
          Expand-Archive -Path ".\ngrok.zip"
          Remove-Item -Path ".\ngrok.zip"

      - name: Authenticate with ngrok using the provided token
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Start an ngrok tunnel for port 3389
        run: .\ngrok\ngrok.exe tcp 3389
