name: CI for Udemy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable TS
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server"-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -Name "RemoteDesktop-UserMode-In-TCP"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      
      # - name: Download and Extract ngrok for creating secure tunnels
        # run: |
          # Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ".\ngrok.zip"
          # Expand-Archive -Path ".\ngrok.zip"
          # Remove-Item -Path ".\ngrok.zip"
          
      - name: Install ngrok using Chocolatey
        run: choco install ngrok -y
        
      - name: Authenticate with ngrok using the provided token
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          
      # - name: Start an ngrok tunnel for port 3389 with specified region
        # run: .\ngrok\ngrok.exe tcp --region=us-cal-1 3389
        
      - name: Setup ngrok region
        run: |
          Add-Content -Path "${env:USERPROFILE}\AppData\Local\ngrok\ngrok.yml" -Value "region: us-cal-1"
          
      - name: Start an ngrok tunnel for port 3389
        run: .\ngrok\ngrok.exe tcp 3389
