name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Enable RDP and change RDP port
        run: |
          # Enable RDP
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
          
          # Enable user authentication for RDP
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
          
          # Change RDP port to 50000
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "PortNumber" -Value 50000
          
          # Restart the Terminal Services service
          Stop-Service TermService -Force
          Start-Service TermService
          
          # Add firewall rule for port 50000
          New-NetFirewallRule -DisplayName "Remote Desktop (TCP-In) 50000" -LocalPort 50000 -Direction Inbound -Protocol TCP -Action Allow | Out-Null
          
          # Reset password for user "runneradmin"
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Set up udemy-py
        run: |
          cd C:\
          # Clone the udemy-py repository
          git clone https://github.com/swargaraj/udemy-py.git
          
          New-Item -ItemType Directory -Path ".\udemy-py\dependencies" -Force
          
          # Download necessary tools: ffmpeg, N_m3u8DL-RE, and Bento4
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip", "C:\ffmpeg.zip")
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.2.1-beta/N_m3u8DL-RE_Beta_win-x64_20240828.zip", "C:\N_m3u8DL-RE.zip")
          (New-Object System.Net.WebClient).DownloadFile("https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-641.x86_64-microsoft-win32.zip", "C:\bento4.zip")
          
          # Extract and delete each archive in the list
          $files = @("ffmpeg.zip", "N_m3u8DL-RE.zip", "bento4.zip")
          foreach ($file in $files) {
              Expand-Archive -Path ".\$file" -DestinationPath ".\udemy-py\dependencies" -Force
              Remove-Item -Path ".\$file"
          }
          
          # Install required Python packages for udemy-py
          py -m pip install -r .\udemy-py\requirements.txt

      - name: Modify constants.py in-place
        run: |
          $filePath = "./udemy-py/constants.py"
          $lineNumber = 90
          $newContent = "        import shutil`n        cols = shutil.get_terminal_size(fallback=(80, 20)).columns"

          $lines = Get-Content $filePath
          if ($lines.Count -ge $lineNumber) {
              $lines[$lineNumber - 1] = $newContent
              Set-Content -Path $filePath -Value $lines
          }

      - name: Test Download
        shell: cmd
        run: |
          cd C:\udemy-py
          $path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          $path += ";C:\udemy-py\dependencies\ffmpeg-master-latest-win64-gpl\bin"
          $path += ";C:\udemy-py\dependencies\N_m3u8DL-RE_Beta_win-x64"
          $path += ";C:\udemy-py\dependencies\Bento4-SDK-1-6-0-641.x86_64-microsoft-win32\bin"
          [System.Environment]::SetEnvironmentVariable("Path", $path, "Machine")
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          Invoke-WebRequest -Uri "https://hustk62-my.sharepoint.com/:t:/g/personal/hieu_hoangduy_hustk62_onmicrosoft_com/EePwwLCA-E1JjP_EyjblvB8Bz8HgW4clgrmCM_FdCkywpQ?e=hsGrSv&download=1" -OutFile ".\udemy-py\cookies.txt"
          $Env:PYTHONIOENCODING = "utf-8"
          py main.py --url https://www.udemy.com/course/csharp-advanced --key 06998ec48a3f4866a8fb3d2831026bb1:408fc6eb8a1182c1ac7ee8458b6521c5 --cookies cookies.txt --captions en_US --srt

      - name: Download and Extract ngrok for creating secure tunnels
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ".\ngrok.zip"
          Expand-Archive -Path ".\ngrok.zip"
          Remove-Item -Path ".\ngrok.zip"
          
      - name: Authenticate with ngrok using the provided token
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Start an ngrok tunnel for port 50000 with specified region
        run: .\ngrok\ngrok.exe tcp --region=us-cal-1 50000
