name: CI for Udemy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable TS
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -Name "RemoteDesktop-UserMode-In-TCP"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Change the default Python version in GitHub-hosted runners
        run: |
          # Rename the key 3.12 to 3.12_Original
          Rename-Item -Path "HKLM:\SOFTWARE\Python\PythonCore\3.12" -NewName "3.12_Original"

          # Rename the key 3.11 to 3.12
          Rename-Item -Path "HKLM:\SOFTWARE\Python\PythonCore\3.11" -NewName "3.12"

          # Rename the key 3.12_Original to 3.11
          Rename-Item -Path "HKLM:\SOFTWARE\Python\PythonCore\3.12_Original" -NewName "3.11"

      - name: Install ngrok using Chocolatey
        run: choco install ngrok -y
        
      - name: Authenticate with ngrok using the provided token
        run: ngrok authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          
      - name: Setup ngrok region
        run: |
          Add-Content -Path "${env:USERPROFILE}\AppData\Local\ngrok\ngrok.yml" -Value "region: us-cal-1"
          
      - name: Start an ngrok tunnel for port 3389
        run: ngrok tcp 3389
