name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable TS
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Change Python version
        run: |
          $path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          $path = $path -replace ";C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64\\Scripts", ""
          $path = $path -replace ";C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64", ""
          $path += ";${{ runner.tool_cache }}\Python\3.12.7\x64\Scripts;${{ runner.tool_cache }}\Python\3.12.7\x64"
          [System.Environment]::SetEnvironmentVariable("Path", $path, "Machine")

      - name: Set up Udemy Downloader
        run: |
          cd C:\
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          git clone https://github.com/hoangduyhieu/udemix.git
          New-Item -Path ".\udemy-py\cookies.txt" -ItemType File -Force
          New-Item -ItemType Directory -Path ".\udemy-py\dependencies" -Force
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip", "C:\ffmpeg-master-latest-win64-gpl.zip")
          Expand-Archive -Path ".\ffmpeg-master-latest-win64-gpl.zip" -DestinationPath ".\udemy-py\dependencies" -Force
          Remove-Item -Path ".\ffmpeg-master-latest-win64-gpl.zip"
          (New-Object System.Net.WebClient).DownloadFile("https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-641.x86_64-microsoft-win32.zip", "C:\Bento4-SDK-1-6-0-641.x86_64-microsoft-win32.zip")
          Expand-Archive -Path ".\Bento4-SDK-1-6-0-641.x86_64-microsoft-win32.zip" -DestinationPath ".\udemy-py\dependencies" -Force
          Remove-Item -Path ".\Bento4-SDK-1-6-0-641.x86_64-microsoft-win32.zip"
          (New-Object System.Net.WebClient).DownloadFile("https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.2.1-beta/N_m3u8DL-RE_Beta_win-x64_20240828.zip", "C:\N_m3u8DL-RE_Beta_win-x64_20240828.zip")
          Expand-Archive -Path ".\N_m3u8DL-RE_Beta_win-x64_20240828.zip" -DestinationPath ".\udemy-py\dependencies" -Force
          Rename-Item -Path ".\udemy-py\dependencies\N_m3u8DL-RE_Beta_win-x64" -NewName "n_m3u8_dl-re"
          Remove-Item -Path ".\N_m3u8DL-RE_Beta_win-x64_20240828.zip"

          $path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          $path += ";C:\udemy-py\dependencies"
          $path += ";C:\udemy-py\dependencies\ffmpeg-master-latest-win64-gpl\bin"  
          $path += ";C:\udemy-py\dependencies\Bento4-SDK-1-6-0-641.x86_64-microsoft-win32\bin"        
          $path += ";C:\udemy-py\dependencies\n_m3u8_dl-re"
          [System.Environment]::SetEnvironmentVariable("Path", $path, "Machine")
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
          $requirements = @"
          certifi==2024.8.30
          charset-normalizer==3.4.0
          colorama==0.4.6
          idna==3.10
          iso8601==2.1.0
          m3u8==6.0.0
          markdown-it-py==3.0.0
          mdurl==0.1.2
          pathvalidate==3.2.1
          pycryptodome==3.21.0
          Pygments==2.18.0
          requests==2.32.3
          rich==13.9.2
          tqdm==4.66.5
          urllib3==2.2.3
          webvtt-py==0.5.1
          "@
          $requirements | Out-File -FilePath ".\udemy-py\requirements2.txt"
          py -m pip install -r ".\udemy-py\requirements2.txt"

      - name: Download and Extract ngrok
        run: |
          Invoke-WebRequest -Uri 'https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip' -OutFile '.\ngrok.zip'
          Expand-Archive -Path '.\ngrok.zip'
          Remove-Item -Path '.\ngrok.zip'

      - name: Authenticate with provided token
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # - name: Setup ngrok region
      #   run: |
      #     Add-Content -Path "${env:USERPROFILE}\AppData\Local\ngrok\ngrok.yml" -Value "region: us-cal-1"

      # - name: Start tunnel for port 3389
      #   run: .\ngrok\ngrok.exe tcp 3389

      - name: Start an ngrok tunnel for port 3389
        run: .\ngrok\ngrok.exe tcp --region=us-cal-1 3389
