name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Udemy Downloader
        shell: bash
        run: |
          # Tải xuống và giải nén
          curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
          curl -L -o N_m3u8DL-RE.zip https://github.com/nilaoda/N_m3u8DL-RE/releases/download/v0.2.1-beta/N_m3u8DL-RE_Beta_win-x64_20240828.zip
          curl -L -o bento4.zip https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-641.x86_64-microsoft-win32.zip

          mkdir temp2
          unzip -q ffmpeg.zip -d temp2
          unzip -q N_m3u8DL-RE.zip -d temp2
          unzip -q bento4.zip -d temp2

          mv temp2/ffmpeg-master-latest-win64-gpl temp2/ffmpeg
          mv temp2/N_m3u8DL-RE_Beta_win-x64 temp2/N_m3u8DL-RE
          mv temp2/Bento4-SDK-1-6-0-641.x86_64-microsoft-win32 temp2/bento4

          mkdir bin
          echo "Moving renamed directories to 'bin' directory..."
          cp -r temp2/ffmpeg bin/ffmpeg
          cp -r temp2/N_m3u8DL-RE bin/N_m3u8DL-RE
          cp -r temp2/bento4 bin/bento4

          # Thiết lập biến PATH cho phiên làm việc hiện tại
          export PATH="${{ github.workspace }}/bin/ffmpeg/bin:${{ github.workspace }}/bin/N_m3u8DL-RE:${{ github.workspace }}/bin/bento4/bin:$PATH"

          # Dọn dẹp
          rm -rf temp2
          rm ffmpeg.zip N_m3u8DL-RE.zip bento4.zip

      - name: Download and Extract ngrok
        shell: bash
        run: |
          curl -L -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
          unzip -q ngrok.zip -d ngrok
          rm ngrok.zip

      - name: Authenticate with ngrok
        shell: bash
        run: |
          ngrokPath="${{ github.workspace }}/ngrok/ngrok.exe"
          cmd.exe /C "$ngrokPath authtoken $NGROK_AUTH_TOKEN"
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start an ngrok tunnel for port 3389
        shell: bash
        run: |
          ngrokPath="${{ github.workspace }}/ngrok/ngrok.exe"
          cmd.exe /C "$ngrokPath tcp --region=us-cal-1 3389"
